collections:
  - common
  - python

excludes:
  - .cspell.json
  - README.md
  - setup.cfg

render_context:
  project:
    name: convert-case
    description: Convert between string cases with built-in case inference.
    version: 1.1.1
    verbose_name: Convert Case
    repository: https://github.com/JoelLefkowitz/convert-case
    documentation: https://convert-case.readthedocs.io
    codacy_id: 3b8afbb8327d424b9990741fd587d7c4

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

  involvement: Owner
  lifecycle: Production
  publisher: PyPi
  
  languages: 
    - Python

  paradigms:
    - Functional

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs