name: Docs

on:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Build the docs
        run: thx docs

      - name: Upload the artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/dist"

  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build

    environment:
      name: Pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
